"""This extension handles errors rising from other commands and cogs

Mostly based on (aka completely yanked from) this example:
https://github.com/PaulMarisOUMary/Discord-Bot/blob/main/cogs/errors.py
"""
import logging

import discord
from discord import app_commands
from discord.ext import commands

from milton.core.bot import Milton
from milton.core.errors import MiltonInputError

log = logging.getLogger(__name__)


class Errors(commands.Cog, name="errors"):
    """Errors handler."""

    def __init__(self, bot: Milton) -> None:
        self.bot = bot
        bot.tree.error(coro=self.__dispatch_to_app_command_handler)

        self.default_error_message = "üï≥Ô∏è There is an error."

    """def help_custom(self):
        emoji = "<a:crossmark:842800737221607474>"
        label = "Error"
        description = "A custom errors handler. Nothing to see here."
        return emoji, label, description"""

    async def __dispatch_to_app_command_handler(
        self,
        interaction: discord.Interaction,
        error: discord.app_commands.AppCommandError,
    ):
        self.bot.dispatch("app_command_error", interaction, error)

    async def __respond_to_interaction(self, interaction: discord.Interaction) -> bool:
        try:
            await interaction.response.send_message(
                content=self.default_error_message, ephemeral=True
            )
            return True
        except discord.errors.InteractionResponded:
            return False

    @commands.Cog.listener("on_error")
    async def get_error(self, event, *args, **kwargs):
        """Error handler"""
        log.error(
            f"! Unexpected Internal Error: (event) {event}, (args) {args}, (kwargs) {kwargs}."
        )

    @commands.Cog.listener("on_command_error")
    async def get_command_error(
        self, ctx: commands.Context, error: commands.CommandError
    ):
        """Command Error handler
        doc: https://discordpy.readthedocs.io/en/master/ext/commands/api.html#exception-hierarchy
        """
        try:
            if ctx.interaction:  # HybridCommand Support
                await self.__respond_to_interaction(ctx.interaction)
                edit = ctx.interaction.edit_original_message
                if isinstance(error, commands.HybridCommandError):
                    error = error.original  # Access to the original error
            else:
                discord_message = await ctx.send(self.default_error_message)
                edit = discord_message.edit

            log.exception(error)

            raise error

        # ConversionError
        except commands.ConversionError as d_error:
            await edit(content=f"üï≥Ô∏è {d_error}")
        # UserInputError
        except commands.MissingRequiredArgument as d_error:
            await edit(
                content=f"üï≥Ô∏è Something is missing. `{ctx.clean_prefix}{ctx.command.name} <{'> <'.join(ctx.command.clean_params)}>`"
            )
        # UserInputError -> BadArgument
        except commands.MemberNotFound or commands.UserNotFound as d_error:
            await edit(
                content=f"üï≥Ô∏è Member `{str(d_error).split(' ')[1]}` not found ! Don't hesitate to ping the requested member."
            )
        # UserInputError -> BadUnionArgument | BadLiteralArgument | ArgumentParsingError
        except (
            commands.BadArgument
            or commands.BadUnionArgument
            or commands.BadLiteralArgument
            or commands.ArgumentParsingError
        ) as d_error:
            await edit(content=f"üï≥Ô∏è {d_error}")
        # CommandNotFound
        except commands.CommandNotFound as d_error:
            await edit(content=f"üï≥Ô∏è Command `{str(d_error).split(' ')[1]}` not found !")
        # CheckFailure
        except commands.PrivateMessageOnly:
            await edit(
                content="üï≥Ô∏è This command canno't be used in a guild, try in direct message."
            )
        except commands.NoPrivateMessage:
            await edit(content="üï≥Ô∏è This is not working as excpected.")
        except commands.NotOwner:
            await edit(content="üï≥Ô∏è You must own this bot to run this command.")
        except commands.MissingPermissions as d_error:
            await edit(
                content=f"üï≥Ô∏è Your account require the following permissions: `{'` `'.join(d_error.missing_permissions)}`."
            )
        except commands.BotMissingPermissions as d_error:
            if not "send_messages" in d_error.missing_permissions:
                await edit(
                    content=f"üï≥Ô∏è The bot require the following permissions: `{'` `'.join(d_error.missing_permissions)}`."
                )
        except (
            commands.CheckAnyFailure
            or commands.MissingRole
            or commands.BotMissingRole
            or commands.MissingAnyRole
            or commands.BotMissingAnyRole
        ) as d_error:
            await edit(content=f"üï≥Ô∏è {d_error}")
        except commands.NSFWChannelRequired:
            await edit(content="üï≥Ô∏è This command require an NSFW channel.")
        # DisabledCommand
        except commands.DisabledCommand:
            await edit(content="üï≥Ô∏è Sorry this command is disabled.")
        # CommandInvokeError
        except commands.CommandInvokeError as d_error:
            await edit(content=f"üï≥Ô∏è {d_error.original}")
        # CommandOnCooldown
        except commands.CommandOnCooldown as d_error:
            await edit(
                content=f"üï≥Ô∏è Command is on cooldown, wait `{str(d_error).split(' ')[7]}` !"
            )
        # MaxConcurrencyReached
        except commands.MaxConcurrencyReached as d_error:
            await edit(
                content=f"üï≥Ô∏è Max concurrency reached. Maximum number of concurrent invokers allowed: `{d_error.number}`, per `{d_error.per}`."
            )
        # HybridCommandError
        except commands.HybridCommandError as d_error:
            await self.get_app_command_error(ctx.interaction, error)
        # Milton Input Errors.
        except MiltonInputError as e:
            await edit(content=f"Cannot parse your input, sorry: {e.msg}")
        except Exception as e:
            pass
            # log.error(e)

    @commands.Cog.listener("on_app_command_error")
    async def get_app_command_error(
        self,
        interaction: discord.Interaction,
        error: discord.app_commands.AppCommandError,
    ):
        """App command Error Handler
        doc: https://discordpy.readthedocs.io/en/master/interactions/api.html#exception-hierarchy
        """
        try:
            await self.__respond_to_interaction(interaction)
            edit = interaction.edit_original_response

            log.exception(error)

            raise error
        except app_commands.CommandInvokeError as d_error:
            if isinstance(d_error.original, discord.errors.InteractionResponded):
                await edit(content=f"üï≥Ô∏è {d_error.original}")
            elif isinstance(d_error.original, discord.errors.Forbidden):
                await edit(
                    content=f"üï≥Ô∏è `{type(d_error.original).__name__}` : {d_error.original.text}"
                )
            else:
                await edit(
                    content=f"üï≥Ô∏è `{type(d_error.original).__name__}` : {d_error.original}"
                )
        except app_commands.CheckFailure as d_error:
            if isinstance(d_error, app_commands.errors.CommandOnCooldown):
                await edit(
                    content=f"üï≥Ô∏è Command is on cooldown, wait `{str(d_error).split(' ')[7]}` !"
                )
            else:
                await edit(content=f"üï≥Ô∏è `{type(d_error).__name__}` : {d_error}")
        except app_commands.CommandNotFound:
            await edit(
                content=f"üï≥Ô∏è Command was not found.. Seems to be a discord bug, probably due to desynchronization.\nMaybe there is multiple commands with the same name, you should try the other one."
            )
        except MiltonInputError as e:
            await edit(content=f"Cannot parse your input, sorry: {e.msg}")
        except Exception as e:
            """
            Caught here:
            app_commands.TransformerError
            app_commands.CommandLimitReached
            app_commands.CommandAlreadyRegistered
            app_commands.CommandSignatureMismatch
            """
            pass
            # log.exception(e)

    @commands.Cog.listener("on_view_error")
    async def get_view_error(
        self, interaction: discord.Interaction, error: Exception, item: any
    ):
        """View Error Handler"""
        try:
            raise error
        except discord.errors.Forbidden:
            pass
        except Exception as e:
            log.exception(e)

    @commands.Cog.listener("on_modal_error")
    async def get_modal_error(self, interaction: discord.Interaction, error: Exception):
        """Modal Error Handler"""
        try:
            raise error
        except discord.errors.Forbidden:
            pass
        except Exception as e:
            log.exception(e)


async def setup(bot: Milton):
    await bot.add_cog(Errors(bot))
